### PR TITLE
Added link to PHP implementation

### PR DESCRIPTION
**Pull request by Rayne**
I added my PHP implementation of Ecoji/Encoji which supports encoding and decoding. The library is available at [Packagist as `rayne/ecoji`](https://packagist.org/packages/rayne/ecoji) and has a 100% test coverage.

### CODE REVIEW

**Comment by keith-turner** [comment]
nice test @Rayne .  I would like to play around with your implementation sometime.   Is there a quick and way to run it from the command line?  If not, don't worry about it.  I can write some PHP.

I think it would be good to post a link to your project at https://www.reddit.com/r/PHP/.  If you are not interested in doing this, I can.

**Comment by Rayne** [comment]
Thanks. I've added a CLI and support for encoding and decoding streams with release `1.1.0`. I will document the details later.

1. Install PHP 7 incl. `mbstring` extension, e.g. `apt install php-cli php-mbstring` on Debian/Ubuntu

1. Install [Composer](https://getcomposer.org/download)

1. Download the package and install Composer's autoloader

   ```bash
   composer require rayne/ecoji
   ```

1. Execute the CLI program

   ```bash
   ./vendor/bin/ecoji
   ```

It could be possible that I will add a `Dockerfile`, snap package and PHAR package later because this is a really serious library.

I don't have a reddit account. Feel free to post a link to the project. :+1:

**Comment by keith-turner** [comment]
@Rayne I posted a link on reddit

**Comment by Rayne** [comment]
Thanks again. The Docker container can be downloaded with `docker pull rayne/ecoji`. More details here: [ecoi-php#docker](https://github.com/Rayne/ecoji-php#docker)

**Pull request merged**
