### PR TITLE
JavaScript Implementation

### PR DESCRIPTION
**Pull request by UmamiAppearance**
BaseEx as a JavaScript Implementation is added to the list.

### CODE REVIEW

**Comment by UmamiAppearance** [comment]
(If you like to see it in action, take a look at the [online converter](https://umamiappearance.github.io/BaseExJS/examples/demo.html#ecoji_v2).)

**Comment by UmamiAppearance** [comment]
I want to update you on some new developments. I now have a CLI for BaseEx available. It is kind of in an alpha stage, but it does its job already.  To use it run:
```sh
npm install --global base-ex-cli
``` 
Now it is callable:
```sh
printf "Hello World" | bex ecoji_v1 
head -c 24 /dev/urandom | bex ecoji_v2
echo "Ecoj V2" | bex ecoji_v1 | bex ecoji_v2 -d
```

I already had the code for the CLI in the pipeline and  I thought this is a more familiar playground for you.

[Github:BaseExCLI](https://github.com/UmamiAppearance/BaseExCLI)
[npm:base-ex-cli](https://www.npmjs.com/package/base-ex-cli)

**Comment by keith-turner** [comment]
I created a little cheap Ubuntu 20.04 ARM64 VM in Azure to test this. I used it to test the go ecoji code on arm for the first time and that worked fine.  

At first I used `sudo apt install npm` and that installed some super old version of npm that could not install bex.  So I tried using snap and that worked fine.  I ran the following commands to test bex and worked great.  How could I build bex from source (cloning your github) instead of using npm?  Is that easy to describe?  If its not easy to describe don't worry about it.  I am not familiar w/ node and npm.

```
$ sudo snap install node --classic
$ sudo npm install --global base-ex-cli
$ cd ~/ecoji/test_scripts
$ encode1_cmd="bex ecoji_v1 -w 0" encode2_cmd="bex ecoji_v2 -w 0" decode_cmd="bex ecoji_v2 -d"  ./ecoji_test.sh
INFO Ecoji V1 encode command : bex ecoji_v1 -w 0
INFO Ecoji V2 encode command : bex ecoji_v2 -w 0
INFO Ecoji decode command    : bex ecoji_v2 -d

INFO checking eight_byte
INFO checking exhaustive
INFO checking five_byte
INFO checking four_byte_1
INFO checking four_byte_2
INFO checking four_byte_3
INFO checking four_byte_4
INFO checking nine_byte_0
INFO checking nine_byte_1
INFO checking nine_byte_2
INFO checking nine_byte_3
INFO checking one_byte
INFO checking phrase
INFO checking seven_byte
INFO checking six_byte
INFO checking three_byte
INFO checking two_byte
INFO checking zero_byte
INFO checking concat_v1_1
INFO checking concat_v1_2
INFO checking concat_v2_1
INFO checking concat_v2_2
INFO checking windows_newline_v2_1
INFO checking windows_newline_v2_2
INFO checking ascii
INFO checking incorrect_v1_padding
INFO checking misplaced_padding_1
INFO checking misplaced_padding_2
INFO checking misplaced_padding_3
INFO checking misplaced_padding_4
INFO checking misplaced_padding_5
INFO checking misplaced_padding_6
INFO checking misplaced_padding_7
INFO checking missing_padding_1
INFO checking missing_padding_2
INFO checking mixed_1
INFO checking mixed_2
INFO checking mixed_3
INFO checking mixed_4
INFO checking mixed_5
INFO checking mixed_6
INFO checking mixed_7
INFO checking non_ecoji_emoji
```

**Comment by UmamiAppearance** [comment]
Hi!

What you now used is the CLI. Which is more or less made for fun, and which hopefully provided you an easier testing experience. The real value of BaseEx is , that you can import it as a library for node or the browser. The steps to use it are described [here](https://github.com/UmamiAppearance/BaseExJS#usage).

When it comes to the CLI - I am sorry - as an Arch Linux user I wasn't thinking too much about old npm and node versions, that are out there... But I am glad you found your way. 

> How could I build bex from source (cloning your github) instead of using npm?

Yeah, I mean, it is JavaScript. There is no real building process involved (yes, the code gets maybe packed differently, minified, etc.). You can just use it, whether you get it from the github repo, npm or a CDN.

**Comment by UmamiAppearance** [comment]
OK. I had to make some small fixes on both the library and the CLI. Now I have a little time to elaborate on this topic.

So typically, when you want a JavaScript package, you would run `npm i <package-name>` inside of your own npm package. Which is in this case:
```console
npm install base-ex
```

When you do that, you get the source code, plus eventually included builds. Also all dependencies as listed inside of `package.json`, but without the `devDependencies`, which you can install by running `npm install` from inside of the package folder.

When you get the code from github (cloning/forking), you get the current source code but without any dependency. Again if you need them you would run `npm install` with the package folder as your current working directory. So, you basically end up with the same result.

If you just want to use the package it really depends on what you are trying to do. If you have a node package and need a dependency you would simple install and import it. If you want to use it directly for lets say a webpage you would rather use a minified build (which are available for BaseEx, eg. the [standalone Ecoji Builds](https://github.com/UmamiAppearance/BaseExJS/tree/main/dist/converters/Ecoji).)

The CLI is also a npm package. It has _base-ex_ as a dependency and _yargs_ as as CLI helper. But a CLI would in this case very unlikely used as a dependency for another project (you could though if you want to) and more likely as a tool for your command line (logic at its finest). Therefore the global installation. The source is just a single file and needs no further packaging.

I hope this is helpful for you. I've tried to break it down as good as possible... I really do not know what your state of knowledge is, so just let me know, what you exactly trying to do or need.

Best regards.

**Comment by keith-turner** [comment]
>     Yeah, I mean, it is JavaScript. There is no real building process involved (yes, the code gets maybe packed differently, minified, etc.). You can just use it, whether you get it from the github repo, npm or a CDN.

Yeah build was not the best description for what I wanted to do.  I wanted to run everything from source. For the go project,one can follow [these instructions](https://github.com/keith-turner/ecoji#building) to run the command line program from source.  So I wanted to do something like :

```
git clone .../BaseExJS.git
git clone .../base-ex-cli.git
# run base-ex-cli using above source code
```

> I really do not know what your state of knowledge is, so just let me know, what you exactly trying to do or need.

I know basically nothing about npm and node, other than what they are conceptually.   So if I did the two git clones mentioned above, would there be a few commands I could run to run base-ex-cli from the cloned source?  I am just guessing, I have not tried this, wondering if I could do something like the following?


```
git clone .../BaseExJS.git
git clone .../base-ex-cli.git
cd BaseExJS
# do something to install it locall
cd ../base-ex-cli
node index.js  # would it use the version of BaseExJS I just installed
```

If this is not easy to do, then don't worry about it.  I know how to run everything locally from source with Java and Go build systems, and each one has its own quirks.

**Comment by UmamiAppearance** [comment]
**For BaseEx:**
```sh
git clone https://github.com/UmamiAppearance/BaseExJS
cd BaseExJS
npm install
```

Now you can play with it. Eg:
```sh
node
```

```js
const bx = require("base-ex");
const ecoji = new bx.Ecoji();
ecoji.encode("Hello World!")
```

**For the CLI:**
```sh
git clone https://github.com/UmamiAppearance/BaseExCLI
cd BaseExCLI
npm install
printf "Hello World!" | ./index.js ecoji_v2
```

**Comment by UmamiAppearance** [comment]
I hope you're not lost in  JavaScript hell... :fire: :upside_down_face:  :fire:

Just a little side note:  
The CLI is now available on the Arch User Repository: [base-ex-cli](https://aur.archlinux.org/packages/base-ex-cli).  
And while I was already refreshing my AUR knowledge, I also provided an ecoji package: [ecoji](https://aur.archlinux.org/packages/ecoji).

**Comment by keith-turner** [comment]
> I hope you're not lost in JavaScript hell...

Not, not lost in JavaScript hell (yet). Have just not had a chance to circle back to this yet.  Hope to take another look soon.

> And while I was already refreshing my AUR knowledge, I also provided an [ecoji](https://aur.archlinux.org/packages/ecoji) package: ecoji.

Thats really neat.

**Comment by keith-turner** [comment]
I was able to run from source.  Thanks for the instructions.  I also wanted to review the source, but I was not able to do that as I don't have the bandwidth ATM.

**Comment by UmamiAppearance** [comment]
Great. Do the review any time.

**Pull request merged**
