### PR TITLE
Add a link to a Rust implementation of the standard

### PR DESCRIPTION
**Pull request by netvl**
Hello,

Recently I've got a need in an emoji-based base64-like encoding in Rust. All Rust libraries I have found were not really nice to use, so I went ahead and implemented your format in Rust. Basically, I went through your code and did almost literal translation of it to Rust, with Rust-idiomatic changes of course. It would be great if you could add a link to my library to the readme file :)

Thanks!

### CODE REVIEW

**Comment by keith-turner** [comment]
@netvl  I was looking over your implementation and I really like what you did with build.rs.  I opened #19 to do that for the Go version of Ecoji.

**Comment by keith-turner** [comment]
@netvl have you mentioned your Rust implementation of Ecoji anywhere?  I think it would be good to spread the word about it.  Could post a link on the Rust subreddit.  Are there other places to mention new rust software?

**Comment by netvl** [comment]
Nope, I didn't :) I guess I'm a bit lazy for that) Yes, I think subreddit is ok, maybe users.rust-lang.org as well.

**Comment by netvl** [comment]
Oh, and BTW, it turned out that I also need a JVM version of ecoji, so I have written a Java implementation as well. I did not publish it yet but hopefully will soon. Expect another pull request from me :)

**Pull request merged**
