### PR TITLE
added swift implementation🎉

### PR DESCRIPTION
**Pull request by robindiddams**
I implemented it in swift 5.0 for a personal project, love to have it up with the others!

### CODE REVIEW

**Comment by robindiddams** [comment]
@keith-turner are you still accepting pr's?

**Comment by keith-turner** [comment]
@Robindiddams please forgive the delay, I will take a look at this over the weekend.   Thanks for the ping.

**Comment by robindiddams** [comment]
sure no worries!

**Comment by keith-turner** [comment]
Sorry for the delay @Robindiddams.  I looked at your impl, I don't know Swift but it looks great.  The emojis in your commit messages are awesome.

**Comment by robindiddams** [comment]
thanks man! I love committing with emojis 💥

**Pull request merged**
