### PR TITLE
Fix table heading in markdown generator

### PR DESCRIPTION
**Pull request by Rayne**
Thanks for the tip regarding the Markdown generator. I haven't had time to look at the tests yet. I will try to add Ecoji v2 to the PHP library this week or next.

### CODE REVIEW

**Comment by keith-turner** [comment]
>  I will try to add Ecoji v2 to the PHP library this week or next.

Ok that would be great.  Increases the chance of finding any major problems w/ V2 before its released.

**Comment by Rayne** [comment]
I started working on it but need more time.

My feedback so far: I like the test script. However, I expect it to break when my custom commands contain spaces. The next thing doesn't look as problematic, but I would prefer that all variables are quoted.

**Comment by Rayne** [comment]
I just discovered with the test cases that the results of my existing Ecoji v1 CLI implementation should not return a final linebreak when terminating. Since there are no wrapping test cases, is this also true when word-wrapping is enabled?

**Comment by Rayne** [comment]
Some other remarks: Instead of passing environment variables, it would also be possible to pass a file to be loaded by the script. This file could then define three functions that are then executed by the test script to encode with Ecoji v1, v2 or decode.

```bash
ecoji_implementation="/home/ubuntu/wrapper-script" \
./ecoji_test.sh
```

The implementation is project specific and could look like this:

```bash
function ecoji_encode_v1 () {
  /home/ubuntu/bin/myEcoji -w 0
}
```

`ecoji_test.sh` would then "source" the implementation file, e.g.

```
source "$ecoji_implementation"

if ! which ecoji_encode_v1; then
  echo "Implementation does not specify ecoji_encode_v1"
  exit 1
fi

# …

	if ! diff <(cat "data/$bare_name.ev1") <(cat "$plain_file" | ecoji_encode_v1); then
		echo "ERROR : Encoding $plain_file using Ecojiv1 did not produce data/$bare_name.ev1"
	fi
```

I personally think it is a good idea to show the `diff` on mismatch.

**Comment by keith-turner** [comment]
> I just discovered with the test cases that the results of my existing Ecoji v1 CLI implementation should not return a final linebreak when terminating. Since there are no wrapping test cases, is this also true when word-wrapping is enabled?

When word wrapping is enabled I would expect a final new line.  Without word wrapping I would not expect a final new line, like below where the shell prompt shows up after because there is no new line.

```
$ echo "ubuntu" | go run cmd/ecoji/main.go -e
💦📹🐬🪅💥🍨☕
$ echo "ubuntu" | go run cmd/ecoji/main.go -e -w 0
💦📹🐬🪅💥🍨☕$ 
```

> I personally think it is a good idea to show the diff on mismatch. 

Wondering if that would be too noisy and hard to interpret w/ multiple failures.  Maybe if there is a diff it could output a file w/ a name like "encode_$bare_name.ev1.diff"?

> Some other remarks: Instead of passing environment variables, it would also be possible to pass a file to be loaded by the script. 

I like that idea.  Could give `$ecoji_implementation` a default value in the script that points to example file in the test dir.  Then someone could just edit that file and run the test script.

**Comment by Rayne** [comment]
> When word wrapping is enabled I would expect a final new line. Without word wrapping I would not expect a final new line, like below where the shell prompt shows up after because there is no new line.

:+1:

> Wondering if that would be too noisy and hard to interpret w/ multiple failures. Maybe if there is a diff it could output a file w/ a name like "encode_$bare_name.ev1.diff"?

In case of failure, I'm usually interested to see all details at once. In my experience, unit testing frameworks show either the first error and halt, or show all errors at once.

**Comment by keith-turner** [comment]
> In case of failure, I'm usually interested to see all details at once. In my experience, unit testing frameworks show either the first error and halt, or show all errors at once.

Seeing it all at once does make it faster and less hassle to consume the results.  I suppose as long as the individual results are well delineated it shouldn't be too noisy.

**Comment by Rayne** [comment]
Encoder for v2 is implemented. I'm following your implementation with the `trim` option. I try to implement the decoder this weekend.

**Pull request merged**
